spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flashsale?useSSL=false&serverTimezone=Asia/Taipei
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flashsale

server:
  port: 8080

logging:
  level:
    root: INFO
